//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calculator.PrintSquare {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pragimtech.com/webservices", ConfigurationName="PrintSquare.SquareWebServiceSoap")]
    public interface SquareWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pragimtech.com/webservices/Square", ReplyAction="*")]
        double Square(double sideOne);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pragimtech.com/webservices/Square", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SquareAsync(double sideOne);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SquareWebServiceSoapChannel : calculator.PrintSquare.SquareWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SquareWebServiceSoapClient : System.ServiceModel.ClientBase<calculator.PrintSquare.SquareWebServiceSoap>, calculator.PrintSquare.SquareWebServiceSoap {
        
        public SquareWebServiceSoapClient() {
        }
        
        public SquareWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SquareWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SquareWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SquareWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Square(double sideOne) {
            return base.Channel.Square(sideOne);
        }
        
        public System.Threading.Tasks.Task<double> SquareAsync(double sideOne) {
            return base.Channel.SquareAsync(sideOne);
        }
    }
}
