//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calculator.PrintRectangle {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pragimtech.com/webservices", ConfigurationName="PrintRectangle.RectangleWebServiceSoap")]
    public interface RectangleWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pragimtech.com/webservices/Rectangle", ReplyAction="*")]
        double Rectangle(double sideOne, double sideTwo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pragimtech.com/webservices/Rectangle", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RectangleAsync(double sideOne, double sideTwo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RectangleWebServiceSoapChannel : calculator.PrintRectangle.RectangleWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RectangleWebServiceSoapClient : System.ServiceModel.ClientBase<calculator.PrintRectangle.RectangleWebServiceSoap>, calculator.PrintRectangle.RectangleWebServiceSoap {
        
        public RectangleWebServiceSoapClient() {
        }
        
        public RectangleWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RectangleWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RectangleWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RectangleWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Rectangle(double sideOne, double sideTwo) {
            return base.Channel.Rectangle(sideOne, sideTwo);
        }
        
        public System.Threading.Tasks.Task<double> RectangleAsync(double sideOne, double sideTwo) {
            return base.Channel.RectangleAsync(sideOne, sideTwo);
        }
    }
}
